config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get 'pages/portfolio', as: 'portfolio_page'

  resources :users, path: "signup", only: [:new, :create]

  resources :articles, path: "blog" do
    resources :commments
  end

  resources :sessions, path: "signin", only: [:new, :create]

  get '/sessions/delete', to: "sessions#destroy"
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/comments.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :articles
  has_many :comments
  validates :username, presence: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id])if logged_in
  end

  def logged_in
    session[:user_id]
  end

  helper_method :logged_in
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    if params[:sort_type] == "recent"
      @articles = Article.all.order(created_at: :desc)
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    # @username = @article.user.username
    @article.user_id = logged_in
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      redirect_to @commentable.article
    else
      render :new
    end
  end

  private

  def load_commentable
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

end

app/views/articles/index.html.erb
<div class="container">
  <%= link_to "New Post", new_article_path %>
  <div class="post">
    <% @articles.each do |article| %>
      <div class="post-title">
        <%= article.title %>
      </div>
      <div class="post-body">
        <%= article.body %>
      </div>
      <div class="post-credits">
        <div class="post-date">
          <%= article.updated_at.strftime("%d %b %Y") %>
        </div>
        <div class="post-user">
          <!-- need to link to show individual user page -->
          by <%= article.user.try(:username) %>
        </div>
        <div class="post-ed">
          <% if logged_in %>
            <%= link_to "edit", edit_article_path(article) %>
            <%= link_to 'del', article_path(article), method: :delete, data: {confirm: "are you sure?"} %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alistair Hill</title>
  <link rel="shortcut icon" href="favicon.ico" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="logo">
    <%= link_to "Alistair Hill", root_path %>
  </div>
  <%= render 'shared/navbar' %>
  <%= yield %>
</body>
</html>

app/views/pages/index.html.erb
<div class="main-container">
  <%= link_to articles_path do %>
    <div class="blog">blog</div>
  <% end %>
  <%= link_to portfolio_page_path do %>
    <div class="portfolio">portfolio</div>
  <% end %>
  <br style="clear: left;" />
  <%= link_to "#privacy" do %>
    <div class="game-port">game stuff</div>
  <% end %>
  <%= link_to "#privacy" do %>
    <div class="contact">contact</div>
  <% end %>
  <br style="clear: left;" />
</div>

app/views/pages/portfolio.html.erb
<div class="main-container">
  <%= link_to articles_path do %>
    <div class="port-1">something</div>
  <% end %>
  <%= link_to "#privacy" do %>
    <div class="port-2">something</div>
  <% end %>
  <br style="clear: left;" />
  <%= link_to "#privacy" do %>
    <div class="port-3">something</div>
  <% end %>
  <%= link_to "#privacy" do %>
    <div class="port-4">something</div>
  <% end %>
  <br style="clear: left;" />
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <% if logged_in %>
    <%= link_to "Sign out", sessions_delete_path %>
  <% else %>
    <%= link_to "Sign up", new_user_path %> -
    <%= link_to "Sign in", new_session_path %> -
  <% end %>
  <%= link_to "Blog", articles_path %>
</div>

app/views/users/new.html.erb
<div class="log-signup-form">
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, autofocus: true, placeholder: ''  %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password, autofocus: true, placeholder: ''  %>
    <br>
    <%= submit_tag "create new account", class: "create" %>
  <% end %>
</div>